### ISSUE TITLE
A little question about hitcon 2018 abyss

### ISSUE THREAD

**Issue by Escapingbug** [david942j/ctf-writeups#2]
Thanks 4 the great challenge! Learning a lot from it, still researching a little. But I found that for abyss 3rd level, you've used ioctl as a solution. Since there's already open, write and lseek in the kvm, can't we just open, lseek and write to `/proc/self/mem`? I want to make sure that if it is told during the game that remote server has no `/proc/self/mem` accessible, thanks.

**Comment by david942j** [comment]
The mode of open is readonly, in this case we should not be able to write `/proc/self/mem`.

**Comment by Escapingbug** [comment]
Oh, that makes sense. I should have been more careful.. Thanks.
